version: '3.8'

services:
  web:
    build: .
    image: vsanthoshraj/student-performance-prediction:latest
    container_name: edusense_app
    ports:
      - "80:80"
    environment:
      - PORT=80
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
      - MYSQL_DATABASE=edusense_db
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    container_name: edusense_db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: edusense_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
